server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.11.101:8848 #配置单点Nacos地址
        server-addr: 192.168.11.101:8888 #配置Nacos集群的nginx负载均衡入口地址

#消费者将去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider


